@echo off
rem DO NOT EDIT THIS FILE
rem CALL IT WITH THE DESIRED ARGS
rem eg: run -inj wx

rem DO NOT USE FULL PATHS EITHER
rem IF ppython IS NOT CORRECT PANDA3D
rem MAKE YOUR OWN RUN (AND GIT IGNORE IT!)
C:/Panda3D-ttn/python/ppython main.py -t cleristonrodini -s 192.168.0.6 -l pt
pause
